---
version: "3.3"

services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nomoney
    command:
      - postgres
      - -c
      - log_statement=all
    volumes:
      - ./data:/var/lib/postgresql/data

  redis:
    image: redis:alpine

  app:
    build: ./
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres/nomoney
    ports:
      - 8080:8080
    volumes:
      - ./:/app/
