---
version: "3.3"

services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nomoney
    command:
      - postgres
      - -c
      - log_statement=all
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
